const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.gamepad,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.progressbar,
		C3.Behaviors.Follow,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.LOS,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Gamepad: 0},
	{grama: 0},
	{madeira: 0},
	{pisomadeira: 0},
	{Sólido: 0},
	{paredescasa: 0},
	{pilar: 0},
	{chãopedra: 0},
	{Arvore: 0},
	{parede: 0},
	{piso: 0},
	{fogão: 0},
	{mesa: 0},
	{tabua: 0},
	{lancheira: 0},
	{parede2: 0},
	{quinaparede: 0},
	{sofa: 0},
	{banco: 0},
	{tv: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Seguir: 0},
	{BarraDeProgresso: 0},
	{VIDA: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{idoso: 0},
	{munição: 0},
	{Esmaecer: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{bullet: 0},
	{CampoDeVisão: 0},
	{galinha: 0},
	{GalinhaDeath: 0},
	{terra: 0},
	{cerca: 0},
	{agua: 0},
	{Âncora: 0},
	{EntradaDeTexto: 0},
	{PlanoDeFundoEmBlocos: 0},
	{VacaDeath: 0},
	{Vaca: 0},
	{Porco: 0},
	{Porcodeath: 0},
	{RatoDeath: 0},
	{Rato: 0},
	{EntradaDeTexto2: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{EntradaDeTexto3: 0},
	{Sprite: 0},
	{Botão: 0},
	{Sprite2: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Gamepad: class extends self.IInstance {},
	grama: class extends self.ITiledBackgroundInstance {},
	madeira: class extends self.ITiledBackgroundInstance {},
	pisomadeira: class extends self.ITiledBackgroundInstance {},
	paredescasa: class extends self.ITiledBackgroundInstance {},
	pilar: class extends self.ITiledBackgroundInstance {},
	chãopedra: class extends self.ITiledBackgroundInstance {},
	Arvore: class extends self.ITiledBackgroundInstance {},
	parede: class extends self.ITiledBackgroundInstance {},
	piso: class extends self.ITiledBackgroundInstance {},
	fogão: class extends self.ITiledBackgroundInstance {},
	mesa: class extends self.ITiledBackgroundInstance {},
	tabua: class extends self.ITiledBackgroundInstance {},
	lancheira: class extends self.ITiledBackgroundInstance {},
	parede2: class extends self.ITiledBackgroundInstance {},
	quinaparede: class extends self.ITiledBackgroundInstance {},
	sofa: class extends self.ITiledBackgroundInstance {},
	banco: class extends self.ITiledBackgroundInstance {},
	tv: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	idoso: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	galinha: class extends self.ISpriteInstance {},
	GalinhaDeath: class extends self.ISpriteInstance {},
	terra: class extends self.ITiledBackgroundInstance {},
	cerca: class extends self.ITiledBackgroundInstance {},
	agua: class extends self.ITiledBackgroundInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	VacaDeath: class extends self.ISpriteInstance {},
	Vaca: class extends self.ISpriteInstance {},
	Porco: class extends self.ISpriteInstance {},
	Porcodeath: class extends self.ISpriteInstance {},
	RatoDeath: class extends self.ISpriteInstance {},
	Rato: class extends self.ISpriteInstance {},
	EntradaDeTexto2: class extends self.ITextInputInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	EntradaDeTexto3: class extends self.ITextInputInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}